// Code generated by MockGen. DO NOT EDIT.
// Source: todolist/internal/pkg/authUtils (interfaces: ITokenHandler)

// Package mock_adapters is a generated GoMock package.
package mock_adapters

import (
	reflect "reflect"
	models "todolist/internal/models"
	auth_utils "todolist/internal/pkg/authUtils"

	gomock "github.com/golang/mock/gomock"
)

// MockITokenHandler is a mock of ITokenHandler interface.
type MockITokenHandler struct {
	ctrl     *gomock.Controller
	recorder *MockITokenHandlerMockRecorder
}

// MockITokenHandlerMockRecorder is the mock recorder for MockITokenHandler.
type MockITokenHandlerMockRecorder struct {
	mock *MockITokenHandler
}

// NewMockITokenHandler creates a new mock instance.
func NewMockITokenHandler(ctrl *gomock.Controller) *MockITokenHandler {
	mock := &MockITokenHandler{ctrl: ctrl}
	mock.recorder = &MockITokenHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITokenHandler) EXPECT() *MockITokenHandlerMockRecorder {
	return m.recorder
}

// GenerateToken mocks base method.
func (m *MockITokenHandler) GenerateToken(arg0 models.User, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockITokenHandlerMockRecorder) GenerateToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockITokenHandler)(nil).GenerateToken), arg0, arg1)
}

// ParseToken mocks base method.
func (m *MockITokenHandler) ParseToken(arg0, arg1 string) (*auth_utils.Payload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseToken", arg0, arg1)
	ret0, _ := ret[0].(*auth_utils.Payload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseToken indicates an expected call of ParseToken.
func (mr *MockITokenHandlerMockRecorder) ParseToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseToken", reflect.TypeOf((*MockITokenHandler)(nil).ParseToken), arg0, arg1)
}

// ValidateToken mocks base method.
func (m *MockITokenHandler) ValidateToken(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockITokenHandlerMockRecorder) ValidateToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockITokenHandler)(nil).ValidateToken), arg0, arg1)
}
