name: Deploy from Docker Hub

on:
  push:
    branches: [main, develop]

jobs:
  deploy:
    runs-on: self-hosted
    environment: production
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy using docker-compose
      run: |
        echo "Deploying from Docker Hub..."
        
        docker pull volnamax1/todolist:latest
        
        docker-compose -f docker-compose.yml -f docker-compose.prod.yml down -v
        docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

        echo "Deployment complete!"
